set(DEPLOY_DIALOG_RUNNER_ROOT_DIR "${BHUMAN_PREFIX}/Src/Apps/DeployDialogRunner")
set(DEPLOY_DIALOG_RUNNER_OUTPUT_DIR "${OUTPUT_PREFIX}/Build/${PLATFORM}/DeployDialogRunner/$<CONFIG>")

file(GLOB_RECURSE DEPLOY_DIALOG_RUNNER_SOURCES CONFIGURE_DEPENDS
    "${DEPLOY_DIALOG_RUNNER_ROOT_DIR}/*.cpp" "${DEPLOY_DIALOG_RUNNER_ROOT_DIR}/*.h")

set(DEPLOY_DIALOG_RUNNER_TREE "${DEPLOY_DIALOG_RUNNER_SOURCES}")

add_executable(DeployDialogRunner EXCLUDE_FROM_ALL ${DEPLOY_DIALOG_RUNNER_SOURCES})

set_property(TARGET DeployDialogRunner PROPERTY RUNTIME_OUTPUT_DIRECTORY "${DEPLOY_DIALOG_RUNNER_OUTPUT_DIR}")
set_property(TARGET DeployDialogRunner PROPERTY FOLDER Apps)

target_include_directories(DeployDialogRunner PRIVATE "${DEPLOY_DIALOG_RUNNER_ROOT_DIR}")
target_compile_definitions(DeployDialogRunner PRIVATE CONFIGURATION=$<CONFIG>)

target_link_libraries(DeployDialogRunner PRIVATE Platform)

source_group(TREE "${DEPLOY_DIALOG_RUNNER_ROOT_DIR}" FILES ${DEPLOY_DIALOG_RUNNER_TREE})
