if(CMAKE_HOST_WIN32)
  add_custom_target(deploy "${BHUMAN_PREFIX}/Util/CallTool/bin/CallTool.exe" CONFIG=$<CONFIG> /c "deploy 192.168.5.xxx -nc" /t Deploy "deploy ip [-b] (restart bhuman) [-d] (delete logs) [-l location] [-p player] [-s scenario] [-t team] [-v volume] [-w wifi]" WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../VS2019")
  set_property(TARGET deploy PROPERTY FOLDER Utils)
  add_dependencies(deploy Nao)
endif()
