#!/bin/bash

set -eu

export scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
export baseDir=$(dirname "${scriptPath}")
cd "$baseDir/Frameworks"

export qtPath=/usr/local/Trolltech/Qt-4.8.6/lib # NOTE: currently not used!

for i in */Versions/4/Qt* lib*; do
  install_name_tool -id @executable_path/../Frameworks/$i $i
done

for i in */Versions/4/Qt* lib* ../plugins/*/* ../bin/moc ../bin/rcc ../bin/qcollectiongenerator ../bin/qhelpgenerator; do
  for j in */Versions/4/Qt* lib*; do
    install_name_tool -change $j @executable_path/../Frameworks/$j $i
  done
done
