#!/bin/bash
cmake.exe -G "Visual Studio 16 2019" -A x64 -S ../Common -B ../../Build/Windows/CMake
if [ ! -e B-Human.sln ]
then
    ln -s ../../Build/Windows/CMake/B-Human.sln B-Human.sln
fi

for c in Debug Develop Release; do
    cmake -DCMAKE_BUILD_TYPE=$c -DBUILD_NAO=ON -G Ninja -S ../Common -B ../../Build/Linux/CMake/$c
done
