// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LightPixel.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LIGHTPIXEL_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LIGHTPIXEL_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated LightPixel is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LIGHTPIXEL_SOURCE)
#define LIGHTPIXEL_DllAPI __declspec(dllexport)
#else
#define LIGHTPIXEL_DllAPI __declspec(dllimport)
#endif  // LIGHTPIXEL_SOURCE
#else
#define LIGHTPIXEL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LIGHTPIXEL_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure LightPixel defined by the user in
 * the IDL file.
 * @ingroup LightPixel
 */
class LightPixel : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::LightPixel that
   * will be copied.
   */
  eProsima_user_DllExport LightPixel(const LightPixel& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::LightPixel that
   * will be copied.
   */
  eProsima_user_DllExport LightPixel(LightPixel&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::LightPixel that
   * will be copied.
   */
  eProsima_user_DllExport LightPixel& operator=(const LightPixel& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::LightPixel that
   * will be copied.
   */
  eProsima_user_DllExport LightPixel& operator=(LightPixel&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::LightPixel object to compare.
   */
  eProsima_user_DllExport bool operator==(const LightPixel& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::LightPixel object to compare.
   */
  eProsima_user_DllExport bool operator!=(const LightPixel& x) const;

  /*!
   * @brief This function sets a value in member r
   * @param _r New value for member r
   */
  eProsima_user_DllExport void r(uint8_t _r);

  /*!
   * @brief This function returns the value of member r
   * @return Value of member r
   */
  eProsima_user_DllExport uint8_t r() const;

  /*!
   * @brief This function returns a reference to member r
   * @return Reference to member r
   */
  eProsima_user_DllExport uint8_t& r();

  /*!
   * @brief This function sets a value in member g
   * @param _g New value for member g
   */
  eProsima_user_DllExport void g(uint8_t _g);

  /*!
   * @brief This function returns the value of member g
   * @return Value of member g
   */
  eProsima_user_DllExport uint8_t g() const;

  /*!
   * @brief This function returns a reference to member g
   * @return Reference to member g
   */
  eProsima_user_DllExport uint8_t& g();

  /*!
   * @brief This function sets a value in member b
   * @param _b New value for member b
   */
  eProsima_user_DllExport void b(uint8_t _b);

  /*!
   * @brief This function returns the value of member b
   * @return Value of member b
   */
  eProsima_user_DllExport uint8_t b() const;

  /*!
   * @brief This function returns a reference to member b
   * @return Reference to member b
   */
  eProsima_user_DllExport uint8_t& b();

 private:
  uint8_t m_r{0};
  uint8_t m_g{0};
  uint8_t m_b{0};

 public:
  typedef LightPixel type;

  eProsima_user_DllExport LightPixel();

  eProsima_user_DllExport ~LightPixel() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LIGHTPIXEL_H_
