// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowState.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LOWSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LOWSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated LowState is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "ImuState.h"
#include "MotorState.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LOWSTATE_SOURCE)
#define LOWSTATE_DllAPI __declspec(dllexport)
#else
#define LOWSTATE_DllAPI __declspec(dllimport)
#endif  // LOWSTATE_SOURCE
#else
#define LOWSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LOWSTATE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure LowState defined by the user in
 * the IDL file.
 * @ingroup LowState
 */
class LowState : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::LowState that will
   * be copied.
   */
  eProsima_user_DllExport LowState(const LowState& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::LowState that will
   * be copied.
   */
  eProsima_user_DllExport LowState(LowState&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::LowState that will
   * be copied.
   */
  eProsima_user_DllExport LowState& operator=(const LowState& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::LowState that will
   * be copied.
   */
  eProsima_user_DllExport LowState& operator=(LowState&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::LowState object to compare.
   */
  eProsima_user_DllExport bool operator==(const LowState& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::LowState object to compare.
   */
  eProsima_user_DllExport bool operator!=(const LowState& x) const;

  /*!
   * @brief This function copies the value in member imu_state
   * @param _imu_state New value to be copied in member imu_state
   */
  eProsima_user_DllExport void imu_state(
      const booster_interface::msg::ImuState& _imu_state);

  /*!
   * @brief This function moves the value in member imu_state
   * @param _imu_state New value to be moved in member imu_state
   */
  eProsima_user_DllExport void imu_state(
      booster_interface::msg::ImuState&& _imu_state);

  /*!
   * @brief This function returns a constant reference to member imu_state
   * @return Constant reference to member imu_state
   */
  eProsima_user_DllExport const booster_interface::msg::ImuState& imu_state()
      const;

  /*!
   * @brief This function returns a reference to member imu_state
   * @return Reference to member imu_state
   */
  eProsima_user_DllExport booster_interface::msg::ImuState& imu_state();

  /*!
   * @brief This function copies the value in member motor_state_parallel
   * @param _motor_state_parallel New value to be copied in member
   * motor_state_parallel
   */
  eProsima_user_DllExport void motor_state_parallel(
      const std::vector<booster_interface::msg::MotorState>&
          _motor_state_parallel);

  /*!
   * @brief This function moves the value in member motor_state_parallel
   * @param _motor_state_parallel New value to be moved in member
   * motor_state_parallel
   */
  eProsima_user_DllExport void motor_state_parallel(
      std::vector<booster_interface::msg::MotorState>&& _motor_state_parallel);

  /*!
   * @brief This function returns a constant reference to member
   * motor_state_parallel
   * @return Constant reference to member motor_state_parallel
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::MotorState>&
  motor_state_parallel() const;

  /*!
   * @brief This function returns a reference to member motor_state_parallel
   * @return Reference to member motor_state_parallel
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::MotorState>&
  motor_state_parallel();

  /*!
   * @brief This function copies the value in member motor_state_serial
   * @param _motor_state_serial New value to be copied in member
   * motor_state_serial
   */
  eProsima_user_DllExport void motor_state_serial(
      const std::vector<booster_interface::msg::MotorState>&
          _motor_state_serial);

  /*!
   * @brief This function moves the value in member motor_state_serial
   * @param _motor_state_serial New value to be moved in member
   * motor_state_serial
   */
  eProsima_user_DllExport void motor_state_serial(
      std::vector<booster_interface::msg::MotorState>&& _motor_state_serial);

  /*!
   * @brief This function returns a constant reference to member
   * motor_state_serial
   * @return Constant reference to member motor_state_serial
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::MotorState>&
  motor_state_serial() const;

  /*!
   * @brief This function returns a reference to member motor_state_serial
   * @return Reference to member motor_state_serial
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::MotorState>&
  motor_state_serial();

 private:
  booster_interface::msg::ImuState m_imu_state;
  std::vector<booster_interface::msg::MotorState> m_motor_state_parallel;
  std::vector<booster_interface::msg::MotorState> m_motor_state_serial;

 public:
  typedef LowState type;

  eProsima_user_DllExport LowState();

  eProsima_user_DllExport ~LowState() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_LOWSTATE_H_
