// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCmd.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_MOTORCMD_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_MOTORCMD_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated MotorCmd is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTORCMD_SOURCE)
#define MOTORCMD_DllAPI __declspec(dllexport)
#else
#define MOTORCMD_DllAPI __declspec(dllimport)
#endif  // MOTORCMD_SOURCE
#else
#define MOTORCMD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTORCMD_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure MotorCmd defined by the user in
 * the IDL file.
 * @ingroup MotorCmd
 */
class MotorCmd : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::MotorCmd that will
   * be copied.
   */
  eProsima_user_DllExport MotorCmd(const MotorCmd& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::MotorCmd that will
   * be copied.
   */
  eProsima_user_DllExport MotorCmd(MotorCmd&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::MotorCmd that will
   * be copied.
   */
  eProsima_user_DllExport MotorCmd& operator=(const MotorCmd& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::MotorCmd that will
   * be copied.
   */
  eProsima_user_DllExport MotorCmd& operator=(MotorCmd&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::MotorCmd object to compare.
   */
  eProsima_user_DllExport bool operator==(const MotorCmd& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::MotorCmd object to compare.
   */
  eProsima_user_DllExport bool operator!=(const MotorCmd& x) const;

  /*!
   * @brief This function sets a value in member mode
   * @param _mode New value for member mode
   */
  eProsima_user_DllExport void mode(uint8_t _mode);

  /*!
   * @brief This function returns the value of member mode
   * @return Value of member mode
   */
  eProsima_user_DllExport uint8_t mode() const;

  /*!
   * @brief This function returns a reference to member mode
   * @return Reference to member mode
   */
  eProsima_user_DllExport uint8_t& mode();

  /*!
   * @brief This function sets a value in member q
   * @param _q New value for member q
   */
  eProsima_user_DllExport void q(float _q);

  /*!
   * @brief This function returns the value of member q
   * @return Value of member q
   */
  eProsima_user_DllExport float q() const;

  /*!
   * @brief This function returns a reference to member q
   * @return Reference to member q
   */
  eProsima_user_DllExport float& q();

  /*!
   * @brief This function sets a value in member dq
   * @param _dq New value for member dq
   */
  eProsima_user_DllExport void dq(float _dq);

  /*!
   * @brief This function returns the value of member dq
   * @return Value of member dq
   */
  eProsima_user_DllExport float dq() const;

  /*!
   * @brief This function returns a reference to member dq
   * @return Reference to member dq
   */
  eProsima_user_DllExport float& dq();

  /*!
   * @brief This function sets a value in member tau
   * @param _tau New value for member tau
   */
  eProsima_user_DllExport void tau(float _tau);

  /*!
   * @brief This function returns the value of member tau
   * @return Value of member tau
   */
  eProsima_user_DllExport float tau() const;

  /*!
   * @brief This function returns a reference to member tau
   * @return Reference to member tau
   */
  eProsima_user_DllExport float& tau();

  /*!
   * @brief This function sets a value in member kp
   * @param _kp New value for member kp
   */
  eProsima_user_DllExport void kp(float _kp);

  /*!
   * @brief This function returns the value of member kp
   * @return Value of member kp
   */
  eProsima_user_DllExport float kp() const;

  /*!
   * @brief This function returns a reference to member kp
   * @return Reference to member kp
   */
  eProsima_user_DllExport float& kp();

  /*!
   * @brief This function sets a value in member kd
   * @param _kd New value for member kd
   */
  eProsima_user_DllExport void kd(float _kd);

  /*!
   * @brief This function returns the value of member kd
   * @return Value of member kd
   */
  eProsima_user_DllExport float kd() const;

  /*!
   * @brief This function returns a reference to member kd
   * @return Reference to member kd
   */
  eProsima_user_DllExport float& kd();

  /*!
   * @brief This function sets a value in member weight
   * @param _weight New value for member weight
   */
  eProsima_user_DllExport void weight(float _weight);

  /*!
   * @brief This function returns the value of member weight
   * @return Value of member weight
   */
  eProsima_user_DllExport float weight() const;

  /*!
   * @brief This function returns a reference to member weight
   * @return Reference to member weight
   */
  eProsima_user_DllExport float& weight();

 private:
  uint8_t m_mode{0};
  float m_q{0.0};
  float m_dq{0.0};
  float m_tau{0.0};
  float m_kp{0.0};
  float m_kd{0.0};
  float m_weight{0.0};

 public:
  typedef MotorCmd type;

  eProsima_user_DllExport MotorCmd();

  eProsima_user_DllExport ~MotorCmd() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_MOTORCMD_H_
