// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RobotDdsJointStatus.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTDDSJOINTSTATUS_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTDDSJOINTSTATUS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated RobotDdsJointStatus is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ROBOTDDSJOINTSTATUS_SOURCE)
#define ROBOTDDSJOINTSTATUS_DllAPI __declspec(dllexport)
#else
#define ROBOTDDSJOINTSTATUS_DllAPI __declspec(dllimport)
#endif  // ROBOTDDSJOINTSTATUS_SOURCE
#else
#define ROBOTDDSJOINTSTATUS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ROBOTDDSJOINTSTATUS_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure RobotDdsJointStatus defined by the
 * user in the IDL file.
 * @ingroup RobotDdsJointStatus
 */
class RobotDdsJointStatus : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object
   * booster_interface::msg::RobotDdsJointStatus that will be copied.
   */
  eProsima_user_DllExport RobotDdsJointStatus(const RobotDdsJointStatus& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object
   * booster_interface::msg::RobotDdsJointStatus that will be copied.
   */
  eProsima_user_DllExport RobotDdsJointStatus(RobotDdsJointStatus&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object
   * booster_interface::msg::RobotDdsJointStatus that will be copied.
   */
  eProsima_user_DllExport RobotDdsJointStatus& operator=(
      const RobotDdsJointStatus& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object
   * booster_interface::msg::RobotDdsJointStatus that will be copied.
   */
  eProsima_user_DllExport RobotDdsJointStatus& operator=(
      RobotDdsJointStatus&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotDdsJointStatus object to compare.
   */
  eProsima_user_DllExport bool operator==(const RobotDdsJointStatus& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotDdsJointStatus object to compare.
   */
  eProsima_user_DllExport bool operator!=(const RobotDdsJointStatus& x) const;

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function sets a value in member index
   * @param _index New value for member index
   */
  eProsima_user_DllExport void index(int32_t _index);

  /*!
   * @brief This function returns the value of member index
   * @return Value of member index
   */
  eProsima_user_DllExport int32_t index() const;

  /*!
   * @brief This function returns a reference to member index
   * @return Reference to member index
   */
  eProsima_user_DllExport int32_t& index();

  /*!
   * @brief This function sets a value in member is_connected
   * @param _is_connected New value for member is_connected
   */
  eProsima_user_DllExport void is_connected(bool _is_connected);

  /*!
   * @brief This function returns the value of member is_connected
   * @return Value of member is_connected
   */
  eProsima_user_DllExport bool is_connected() const;

  /*!
   * @brief This function returns a reference to member is_connected
   * @return Reference to member is_connected
   */
  eProsima_user_DllExport bool& is_connected();

  /*!
   * @brief This function sets a value in member temperature
   * @param _temperature New value for member temperature
   */
  eProsima_user_DllExport void temperature(int32_t _temperature);

  /*!
   * @brief This function returns the value of member temperature
   * @return Value of member temperature
   */
  eProsima_user_DllExport int32_t temperature() const;

  /*!
   * @brief This function returns a reference to member temperature
   * @return Reference to member temperature
   */
  eProsima_user_DllExport int32_t& temperature();

  /*!
   * @brief This function sets a value in member is_limited
   * @param _is_limited New value for member is_limited
   */
  eProsima_user_DllExport void is_limited(int32_t _is_limited);

  /*!
   * @brief This function returns the value of member is_limited
   * @return Value of member is_limited
   */
  eProsima_user_DllExport int32_t is_limited() const;

  /*!
   * @brief This function returns a reference to member is_limited
   * @return Reference to member is_limited
   */
  eProsima_user_DllExport int32_t& is_limited();

  /*!
   * @brief This function sets a value in member status_code
   * @param _status_code New value for member status_code
   */
  eProsima_user_DllExport void status_code(int32_t _status_code);

  /*!
   * @brief This function returns the value of member status_code
   * @return Value of member status_code
   */
  eProsima_user_DllExport int32_t status_code() const;

  /*!
   * @brief This function returns a reference to member status_code
   * @return Reference to member status_code
   */
  eProsima_user_DllExport int32_t& status_code();

  /*!
   * @brief This function sets a value in member temperature_level
   * @param _temperature_level New value for member temperature_level
   */
  eProsima_user_DllExport void temperature_level(int32_t _temperature_level);

  /*!
   * @brief This function returns the value of member temperature_level
   * @return Value of member temperature_level
   */
  eProsima_user_DllExport int32_t temperature_level() const;

  /*!
   * @brief This function returns a reference to member temperature_level
   * @return Reference to member temperature_level
   */
  eProsima_user_DllExport int32_t& temperature_level();

 private:
  std::string m_name;
  int32_t m_index{0};
  bool m_is_connected{false};
  int32_t m_temperature{0};
  int32_t m_is_limited{0};
  int32_t m_status_code{0};
  int32_t m_temperature_level{0};

 public:
  typedef RobotDdsJointStatus type;

  eProsima_user_DllExport RobotDdsJointStatus();

  eProsima_user_DllExport ~RobotDdsJointStatus() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTDDSJOINTSTATUS_H_
