#!/bin/bash
#
# This script generates the documentations for the CABSL behaviors.
# They are stored under "Build/Documentation".
#
# Author: Thomas Röfer

usage()
{
  echo >&2 "usage: $0 { options }"
  echo >&2 "  options:"
  echo >&2 "    -h             show this help"
  echo >&2 "    -s <scenario>  selected scenario"
  exit 1
}

set -eu

basePath=$(cd "$(dirname "$(which "$0")")" && pwd)
scenario="$(grep -E "^[ 	]*scenario[ 	]*=" <"$basePath/../../Config/settings.cfg" | sed "s%[^=]*=[ 	]*\([A-Za-z_]*\).*%\1%")"

while [ $# -gt 0 ]; do
  case $1 in
    "-h")
      usage
      ;;
    "-s")
      shift
      if [ $# -gt 0 ]; then
        scenario=$1
      else
        echo >&2 "error: parameter of '-s' missing"
        usage
      fi
      ;;
    -*)
      echo >&2 "error: unknown option '$1'"
      usage
      ;;
    *)
      break
      ;;
  esac
  shift
done

if [ -z "$(which java)" ]; then
  echo >&2 "error: cannot find java"
  exit 1
fi

jarPath="$basePath/../../Util/CABSL/cabsl-doc-generator-v3.jar"
tmpPath=/tmp/cabslDocumentation2.tmp
outputDir="$basePath/../../Build/Documentation"

echo "Creating graphs for SkillBehaviorControl..."
configPath="$basePath/../../Config/Scenarios/$scenario/skillBehaviorControl.cfg"
if [ ! -f "$configPath" ]; then
  configPath="$basePath/../../Config/Scenarios/Default/skillBehaviorControl.cfg"
fi

selectOptions="$(grep -R "select_option(.*//@" "$basePath/../../Src/Modules/BehaviorControl/SkillBehaviorControl/Options"/* | sed -e 's%.*//@%%' -e 's% *$%%' | tr '\n' '|' | sed 's%\|$%%')"
tr <"$configPath" '\n' ' ' \
| tr ';' '\n' \
| tr -d ' ' \
| sed -e 's%,]%]%' -e 's%$%;%' \
| grep -E "^($selectOptions)=" >"$tmpPath"
java -jar "$jarPath" -n SkillBehaviorControl -sel "$tmpPath" -od "$outputDir" -oh "$basePath/../../Src/Modules/BehaviorControl/SkillBehaviorControl/SkillBehaviorControl.h" \
| grep -v 'Warning: Unresolvable #include statements'

echo "Creating graphs for FallDownStateProvider..."
java -jar "$jarPath" -n FallDownStateProvider -od "$outputDir" -oh "$basePath/../../Src/Modules/Sensing/FallDownStateDetector/FallDownStateProvider.h" \
| grep -v 'Warning: Unresolvable #include statements'

rm "$tmpPath"
