#!/bin/bash
#
# This script generates a number of svg files from the CABSL behaviors.
# They are stored under "Build/Documentation".
#
# Author: Thomas Röfer

usage()
{
  echo >&2 "usage: $0 { options }"
  echo >&2 "  options:"
  echo >&2 "    -h             show this help"
  echo >&2 "    -p             output pdf instead of svg"
  echo >&2 "    -s <scenario>  selected scenario"
  exit 1
}

set -eu

basePath=$(cd "$(dirname "$(which "$0")")" && pwd)
scenario="$(grep -E "^[ 	]*scenario[ 	]*=" <"$basePath/../../Config/settings.cfg" | sed "s%[^=]*=[ 	]*\([A-Za-z_]*\).*%\1%")"

dot="${basePath}/../../Util/dot/dot"
if [ -e /proc/version ]; then
  if [ ! -z "`grep Microsoft </proc/version`" ]; then
    dot="${basePath}/../../Util/dot/dot.exe"
  fi
fi

pdf=

while [ $# -gt 0 ]; do
  case $1 in
    "-h")
      usage
      ;;
    "-p")
      pdf=-p
      ;;
    "-s")
      shift
      if [ $# -gt 0 ]; then
        scenario=$1
      else
        echo >&2 "error: parameter of '-s' missing"
        usage
      fi
      ;;
    -*)
      echo >&2 "error: unknown option '$1'"
      usage
      ;;
    *)
      break
      ;;
  esac
  shift
done

echo "Creating graphs for SkillBehaviorControl..."
mkdir -p "${basePath}/../../Build/Documentation/SkillBehaviorControl"
cd "${basePath}/../../Build/Documentation/SkillBehaviorControl"

(
  echo "option PlaySoccer"
  echo "initial_state selectOption"
  grep -E "^(playingOptions|[ 	]*[A-Z][A-Za-z0-9]*)" "${basePath}/../../Config/Scenarios/$scenario/skillBehaviorControl.cfg" \
  | sed -e "s%^[ 	]*\([A-Z][A-Za-z0-9]*\).*%call \1%" -e "s%^playingOptions.*%option HandleGameState|state playing%" \
  | tr '|' '\n'
) >data.tmp

find ../../..//Src/Modules/BehaviorControl/SkillBehaviorControl/Options ../../..//Src/Modules/BehaviorControl/SkillBehaviorControl/Skills -name "*.cpp" \
| xargs "${basePath}/../../Util/CABSL/createGraphs" -a data.tmp -m SkillBehaviorControl -d "$dot" $pdf

rm data.tmp

cd "${basePath}/../../Src/"

while read line; do
  echo "Creating graphs for ${line% *}..."
  mkdir -p "${basePath}/../../Build/Documentation/${line% *}"
  cd "${basePath}/../../Build/Documentation/${line% *}"
  "${basePath}/../../Util/CABSL/createGraphs" -d "$dot" $pdf "${basePath}/../../Src/${line##* }"
done <<<\
"BallSearch Modules/BehaviorControl/StrategyBehaviorControl/BallSearch.cpp
FallDownStateProvider Modules/Sensing/FallDownStateDetector/FallDownStateProvider.h
PhotoModeEngine Modules/MotionControl/MotionEngine/PhotoModeEngine.cpp"
