#!/bin/bash
scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
basePath=$(dirname "${scriptPath}")
cd "${basePath}/../../Config/Robots"

for i in `ls | grep -v Default | grep -v Nao | grep -v robots.cfg | grep -v "^.$"`; do
  cd "$i"
  if [ -e "Body/jointCalibration.cfg" ]; then
    git log -1 --pretty="tformat:$(printf "%-18s" $(basename $i)) Joints: %s (%an, %ar)" $* Body/jointCalibration.cfg | cat
  else
    echo "$(printf "%-18s" $(basename $i)) Joints: MISSING" | cat
  fi
  cd ..
  if [ -z "`ls */$i/cameraCalibration.cfg 2>/dev/null`" ]; then
    echo "                   Camera: MISSING" | cat
  else
    for j in `ls */$i/cameraCalibration.cfg`; do
      git log -1 --pretty="tformat:$(printf "%18s" $(dirname $(dirname $j))) Camera: %s (%an, %ar)" $* $j | cat
    done
  fi
done
