#!/bin/bash
# Checks whether modules and skills actually use the requirements
# that they declare. It lists the requirements that are not used.

cd "$(dirname "$(which "$0")")/../../Src/Modules"

WORDSTART="\\<"
if [ "`uname`" = "Darwin" ]; then
  WORDSTART="[[:<:]]"
fi

grep -ER "^(MAKE_MODULE|SKILL_IMPLEMENTATION)\(" \
| sed 's%:.*%%' \
| sort \
| while read CPP; do
  H="${CPP%.*}.h"
  if [ ! -f "$H" ]; then
    H="$CPP"
    CPP=
  fi
  PROVIDES="$(grep "^ *PROVIDES" "$H" | sed -e 's%^[^(]*(%%' -e 's%).*%%' | sort)"
  MATCH="$(tr <<<"$PROVIDES" '\n' '|' | sed -e 's%|$%%' -e 's%^$%SOMETHING_THAT_NEVER_OCCURS%')"
  REQUIRES="$(grep -E "^ *(REQUIRES|USES)" "$H" | sed -e 's%^[^(]*(%%' -e 's%).*%%' | grep -vE "$MATCH" | sort)"
  MATCH="$(tr <<<"$REQUIRES" '\n' '|' | sed 's%|$%%')"
  OTHER=
  if [ ! -z "$(grep 'SkillBehaviorControl\.cpp' <<<"$CPP")" ]; then
    OTHER="$(find "$(dirname "$CPP")/Options" -name "*.h")"
  elif [ ! -z "$(grep 'FallDownStateProvider\.cpp' <<<"$CPP")" ]; then
    OTHER="$(dirname "$CPP")/Options.h"
  elif [ ! -z "$(grep KeyframeMotionEngine <<<"$CPP")" ]; then
    OTHER="$(find "$(dirname "$CPP")/KeyframeMotionLibs" -name "*.h" -o -name "*.cpp")"
  elif [ ! -z "$(grep 'WalkingEngine\.cpp' <<<"$CPP")" ]; then
    OTHER="$(find "$(dirname "$CPP")/WalkLibs" -name "*.h" -o -name "*.cpp")"
  fi
  USED="$(cat $H $CPP $OTHER \
  | sed "s%$WORDSTART\\([A-Za-z][A-Za-z0-9_]*\\)%|\\1|%g" \
  | tr '|' '\n' \
  | grep -E "^the($MATCH)$" \
  | sort \
  | uniq \
  | sed 's%^the%%')"
  DIFF="$(diff --side-by-side --suppress-common-lines <(echo "$REQUIRES") <(echo "$USED"))"
  if [ ! -z "$DIFF" ]; then
    echo "$H: $(sed <<<"$DIFF" 's%	.*%%' | tr '\n' ',' | sed 's%,$%%')"
  fi
done
