#!/bin/bash
# Copies all log files from mounted USB drives with names that
# end with "_B-HUMAN". On Windows, the name of the USB drive is
# ignored.

set -e

basePath=$(cd "$(dirname "$(which "$0")")" && pwd)

usage()
{
  echo "usage: $0 [-d | --just-delete] [<targetDir>]" >&2
  echo " -d             Delete log files after copying." >&2
  echo " --just-delete  Just delete log files." >&2
  exit 1
}

copy=true
delete=false
targetDir=${basePath}/../../Config/Logs
while true; do
  case $1 in
    "")
      break;
      ;;
    "-d" | "/d")
      delete=true
      ;;
    "--just-delete" | "/just-delete")
      delete=true
      copy=false
      ;;
    "-h" | "/h" | "/?" | "--help")
      usage
      ;;
    -*)
      echo "unknown option: $1" >&2
      usage
      ;;
    *)
      targetDir=$1
      ;;
  esac
  shift
done

set -eu

files=$(ls /mnt/*_B-HUMAN/logs/*_*_*.log /media/*_B-HUMAN/logs/*_*_*.log /media/$USER/*_B-HUMAN/logs/*_*_*.log /cygdrive/*/logs/*_*_*.log /Volumes/*_B-HUMAN/logs/*_*_*.log 2>/dev/null || true)

if [ $copy = true -a ! -z "$files" ]; then
  targetPath="$targetDir/$(date +%F-%H-%M)"
  mkdir -p "$targetPath"
  while read path; do
    if [ ! -z "$path" ]; then
      echo "Copying logs from $(dirname "$path") ..."
      name=$(basename $path | sed "s%_.*%%")
      mkdir -p "$targetPath/$name"
      cp "$path" "$targetPath/$name/"
      if [ ! -z "$(ls "$(dirname "$path")"/bhumand* 2>/dev/null || true)" ]; then
        cp "$(dirname "$path")"/bhumand* "$targetPath/$name/"
      fi
    fi
  done <<<"$files"
fi

if $delete; then
  while read path; do
    if [ -e "$path" ]; then
      echo "Deleting logs from $(dirname "$path") ..."
      rm "$(dirname "$path")"/*
    fi
  done <<<"$files"
fi
