#!/bin/bash
# Copies all log files from mounted USB drives with names that
# end with "_B-HUMAN". On Windows, the name of the USB drive is
# ignored.

set -e

basePath=$(cd "$(dirname "$(which "$0")")" && pwd)

usage()
{
  echo "usage: $0 [-d | --just-delete] [<targetDir>]" >&2
  echo "  options:"
  echo "    -d             Delete log files after copying." >&2
  echo "    --just-delete  Just delete log files." >&2
  echo "  examples:"
  echo "    $0"
  echo "    $0 -d ../../Config/Logs"
  echo "    $0 sftp://user@host:/path"
  echo "    $0 --just-delete"
  exit 1
}

copy=true
delete=false
targetDir=${basePath}/../../Config/Logs
mkdir1=
mkdir2="xargs mkdir -p"
cp1=
cp2="xargs cp"
cmd=xargs
while true; do
  case $1 in
    "")
      break;
      ;;
    "-d" | "/d")
      delete=true
      ;;
    "--just-delete" | "/just-delete")
      delete=true
      copy=false
      ;;
    "-h" | "/h" | "/?" | "--help")
      usage
      ;;
    -*)
      echo "unknown option: $1" >&2
      usage
      ;;
    *)
      targetDir=$1
      if [ ! -z "$(grep <<<"$targetDir" "^sftp://.*:")" ]; then
        host="$(sed <<<"$targetDir" "s%^sftp://\([^:]*\).*%\1%")"
        targetDir="$(sed <<<"$targetDir" "s%^sftp://[^:]*:%%")"
        mkdir1="-mkdir"
        mkdir2="sftp -qb - $host"
        cp1=put
        cp2="sftp -qb - $host"
      fi
      ;;
  esac
  shift
done

set -eu

targetPath="$targetDir/$(date +%F-%H-%M)"

files=$(ls /mnt/*_B-HUMAN/logs/*_*_*.log /media/*_B-HUMAN/logs/*_*_*.log /media/$USER/*_B-HUMAN/logs/*_*_*.log /run/media/$USER/*_B-HUMAN/logs/*_*_*.log /cygdrive/*/logs/*_*_*.log /Volumes/*_B-HUMAN/logs/*_*_*.log 2>/dev/null || true)

if [ $copy = true -a ! -z "$files" ]; then
  echo "$mkdir1 \"$targetPath\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
  while read path; do
    if [ ! -z "$path" ]; then
      echo "Copying $path ..."
      name=$(basename $path | sed "s%_.*%%")
      echo "$mkdir1 \"$targetPath/$name\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
      echo "$cp1 \"$path\"" "\"$targetPath/$name/\"" | $cp2 >/dev/null
    fi
  done <<<"$files"
fi

files2=$(ls /mnt/*_B-HUMAN/logs/bhumand*.log /media/*_B-HUMAN/logs/bhumand*.log /media/$USER/*_B-HUMAN/logs/bhumand*.log /run/media/$USER/*_B-HUMAN/logs/bhumand*.log /cygdrive/*/logs/bhumand*.log /Volumes/*_B-HUMAN/logs/bhumand*.log 2>/dev/null || true)

if [ $copy = true -a ! -z "$files2" ]; then
  echo "$mkdir1 \"$targetPath\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
  while read path; do
    if [ ! -z "$path" ]; then
      echo "Copying $path ..."
      name="$(grep " Hi, I am " "$path" | head -1 | sed "s%[^ ]* Hi, I am \(.*\)\.%\1%")"
      echo "$mkdir1 \"$targetPath/$name\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
      echo "$cp1 \"$path\"" "\"$targetPath/$name/\"" | $cp2 >/dev/null
    fi
  done <<<"$files2"
fi

if $delete; then
  while read path; do
    if [ -e "$path" ]; then
      echo "Deleting logs from $(dirname "$path") ..."
      rm "$(dirname "$path")"/*
    fi
  done <<<"$files
$files2"
fi
