#!/bin/bash
# This script displays a deploy dialog on macOS and Linux. It
# asks for command line options for the script 'deploy' and
# then calls that script with these options. It remembers these
# options in the file 'deploy-options.txt' and reuses them the
# next time it is called. It can used at the end of a build
# process in an IDE to directly deploy the code.

cd "$(dirname "$(which "$0")")"

CONFIGURATION="$1"

if [ -z "$(ls 2>/dev/null ../../Config/Robots/*/network.cfg)" ]; then
  NAME_TO_IP=cat
  IP_TO_NAME=cat
else
  NAME_TO_IP=`echo "sed"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^lan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\1/\2/%"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^wlan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\1/\2/%" | tr '[:upper:]' '[:lower:]'`
  NAME_TO_IP=`tr '\n' ' ' <<<"$NAME_TO_IP"`
  IP_TO_NAME=`echo "sed"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^lan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\2/\1/%"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^wlan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\2/\1/%" | tr '[:upper:]' '[:lower:]'`
  IP_TO_NAME=`tr '\n' ' ' <<<"$IP_TO_NAME"`
fi

HELP="$(./deploy --help | grep -v -E "^(usage|  (options|examples):|    \.|    -(h|k|nc|nr|r))" | sed -e 's% *(.*%%' -e 's%^ *\(-.\)[^a-z<]*\([a-z][^<]*\)$%  \1 (\2)%' -e 's%^ *\(-. <[^>]*>\( <[^>]*>\)*\).*$%  \1%')"

if [ -e deploy-options.txt ]; then
  OPTIONS=`cat deploy-options.txt`
else
  OPTIONS=-b
fi

if [ ! -z "$OPTIONS" ]; then
  OPTIONS=" $OPTIONS"
fi

if [ -e ../../Config/Scenes/Includes/connect.con ]; then
  COMMAND="`head -1 ../../Config/Scenes/Includes/connect.con | sed "s%sc Remote \([\.0-9]*\)%\1%"`"
  COMMAND=`$IP_TO_NAME <<<"$COMMAND"`
  COMMAND="$COMMAND$OPTIONS"
else
  COMMAND="<robot>$OPTIONS"
fi

if [ "$(uname)" == "Darwin" ]; then
  BHDIR="$(cd "$(dirname "$(which "$0")")/../.."; pwd)"
  HELP="$(sed <<<"$HELP" -e 's% (%    	(%' -e 's% <%	<%' | tr '\n' X | sed -e 's%X$%%' -e 's%X%\\n%g')"
  COMMAND=`osascript <<-APPLESCRIPT
    tell application "Xcode"
      activate
      display dialog "usage:    <robot> {options}\noptions:\n$HELP" with title "Deploy" with icon file POSIX file "$BHDIR/Util/SimRobot/Src/SimRobot/Icons/SimRobot.icns" default answer "$COMMAND" buttons {"Cancel ", "Deploy"} default button 2
      if button returned of result = "Deploy" then
        return (text returned of result) as string
      else
        return ""
      end if
    end tell
    APPLESCRIPT
  `
else
  HELP="$(sed <<<"$HELP" -e 's% (%    	(%' -e 's% <%	<%')"
  HELP="usage:    <robot> {options}
options:
$HELP"
  HELP=$(sed -e ';=' <<<"$HELP" | sed '-e N;s%\n% %' | sed -e 's%^\([0-9]*\) \(.*\)$%pack [ttk::label .frame1.label\1 -text \"\2\" -font \"Mono 10\"] -side top -anchor w%')
  COMMAND=`wish <<EOF
ttk::setTheme clam
wm title . "Deploy"
wm iconphoto . [image create photo .icon -file ../../Util/SimRobot/Src/SimRobot/Icons/SimRobot.png ]
wm attribute . -type dialog
set inputcommand "$COMMAND"
frame .frame1
$HELP
pack .frame1 -fill both -expand 1 -padx 10
frame .frame2
pack .frame2 -fill both -expand 1 -padx 10 -pady 5
pack [ttk::entry .frame2.entry -textvariable inputcommand -width 50] -fill x -pady 5
pack [ttk::button .frame2.deploy -text "Deploy" -command { puts \\\$inputcommand; exit }] -side right
pack [ttk::button .frame2.cancel -text "Cancel" -command exit] -side right -padx 5
bind . <Return> { .frame2.deploy invoke }
bind . <Escape> { .frame2.cancel invoke }
EOF`
fi

if [ ! -z "$COMMAND" ]; then
  NAME=`sed "s% *\([^ ]*\).*%\1%" <<<"$COMMAND"`
  IP=`$NAME_TO_IP <<<"$NAME"`
  echo "$COMMAND" | sed "s% *[^ ]* *%%" >deploy-options.txt
  ../Common/deploy $CONFIGURATION -nc -k `echo "$COMMAND" | sed -e "s% -a%%" -e "s%<robot>%%"`
fi
