#!/bin/bash
# Start the version of SimRobot that was compiled most recently and
# connect to a remote robot via UDP. Locally, the robot is shown
# wearing a black jersey.

source "$(dirname "$(which "$0")")/digitalTwinRed" $*
