#!/bin/bash

scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
basePath=$(dirname "${scriptPath}")

cd "${basePath}"
teamList=../../Config/teamList.cfg
gameController=../../Util/GameController/config

echo "teams = [" >${teamList}
sed <${gameController}/spl/teams.cfg \
  -e "s%ä%ae%g" \
  -e "s%ö%oe%g" \
  -e "s%ü%ue%g" \
  -e "s%Ä%oe%g" \
  -e "s%Ö%ue%g" \
  -e "s%Ü%oe%g" \
  -e "s%ß%ss%g" \
  -e "s% %-%g" \
  -e "s%\(.*\)=\([^,]*\).*%  {number = \1; name = \"\2\";},%" >>${teamList}
tail -n +2 ${gameController}/spl_mixedteam/teams.cfg \
| sed \
  -e "s%ä%ae%g" \
  -e "s%ö%oe%g" \
  -e "s%ü%ue%g" \
  -e "s%Ä%oe%g" \
  -e "s%Ö%ue%g" \
  -e "s%Ü%oe%g" \
  -e "s%ß%ss%g" \
  -e "s% %-%g" \
  -e "s%\(.*\)=\([^,]*\).*%  {number = \1; name = \"\2\";},%" >>${teamList}
echo "];" >>${teamList}
