#!/bin/bash
# A simple script to display the referee signals sent to the GameController.
# Just start the GameController, determine the log file that it is writing
# to and open the log file with this script. Whenever referee signals arrive,
# they will be written to the terminal.
# On macOS, the parameter can also be omitted. In that case, the log file is
# determined automatically.

signals=(none kickInBlue kickInRed goalKickBlue goalKickRed cornerKickBlue cornerKickRed goalBlue goalRed pushingFreeKickBlue pushingFreeKickRed fullTime substitutionBlue substitutionRed)

if [ $# -gt 0 ]; then
  log="$1"
elif [ "$(uname)" == "Darwin" ]; then
  log="$(ls -drt ~/Library/Application\ Support/GameController/logs/*.yaml | tail -1)"
fi

tail -f "$log" \
  | grep --line-buffered UkdydP \
  | while read i; do
      output="$(sed 's%[^:]*: %%' <<<"$i" \
        | base64 -d \
        | hexdump -s 5 -n 3 -e '3/1 "%d "' -e '"\n"')"
      IFS=' ' read player team signal <<<"$output"
      echo "team $team, player $player: ${signals[$signal]}"
    done
