#!/bin/sh
##
## Copyright (C) 2014 Aldebaran
##
## Call chest-harakiri to poweroff the machine.
## This is called by systemd-shutdown; see systemd-halt.service(8)
##

HARAKIRI=/opt/bhuman/libexec/chest-harakiri
SETEARS=/opt/aldebaran/bin/setears
CAMRESET=/opt/aldebaran/libexec/reset-cameras.sh

ACTION=$1

if ! command -v "$HARAKIRI" >/dev/null; then
    echo >&2 "$HARAKIRI not found, system will not poweroff shutdown or reboot"
    exit 1
fi

if test -x ${SETEARS}; then
  ${SETEARS} 10 >/dev/null
fi

# Put Pepper >=1.8 cameras into reset,
# otherwise the HW will not reboot correctly
${CAMRESET} hold

case "$ACTION" in
poweroff|halt)
    "$HARAKIRI"
    ;;
reboot)
    "$HARAKIRI" -r
    ;;
esac
