#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if 'GIT' rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$('GIT' config hooks.allownonascii)

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$('GIT' diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0')"
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  'GIT' config hooks.allownonascii true"
	echo
	exit 1
fi

# If you want to forbid tab characters in files, set this variable to true.
checkTabs=$('GIT' config hooks.checkTabs)

if [ "$checkTabs" = "true" ]
then
        # find changed files with tab characters (ignore files in Make
        # directories)
	filesWithTabs=""
	for file in "$('GIT' diff --cached --name-only)"
	do
		if [ "$(echo "$file" | grep -E '^Src/.*')" -o "$(echo "$file" | grep -E '^Util/SimRobot/Src/.*')" ]
		then
			if [ "$('GIT' diff --cached --inter-hunk-context=0 -- "$file" | grep -E '^\+' | LC_ALL=C tr -d -c '\t')" ]
			then
				filesWithTabs="$filesWithTabs $file"
			fi
		fi
	done
        # list files with tab characters an exit with non-zero
	if [ "${#filesWithTabs}" -gt 0 ]
	then
		echo "Error: Attempt to add tab characters."
		for file in "$filesWithTabs"
		do
			echo "\t$file"
		done
		exit 1
	fi
fi

# check if there are trailing whitespaces
exec 'GIT' diff-index --check --cached $against --
