#!/bin/sh
# Start the version of the bush that was compiled most recently.
# This script can be launched from the Finder.

cd "$(dirname "$(which "$0")")"
open `ls -t ../../Build/macOS/bush/*/* | head -1 | sed "s%\(.*/\).*%\1bush.app%"`