#!/bin/bash
# This script is used to format a logging drive.
# It formats a single USB drive as exFAT with MBR.
# The drive will be named "<number>_B-Human".
# The number is assumed to be labeled on the drive.
# Only tested on macOS Ventura.

Info="$(diskutil list external physical | grep '^ *0:' | sed -e 's%^[^*]*\*%%' -e 's%^\(.*B\) *\(.*\)%/dev/\2 (\1)%')"
Device=$(sed 's% .*%%' <<<"$Info")

NumLines=$(echo "$Device" | wc -l)

# If there are more than 1 line, print an error message and exit
if [[ $NumLines -gt 1 ]]; then
    echo "Error: Multiple drives are inserted. To ensure correct USB drive labels, please insert them one by one."
    exit 1
fi

# An example of a device name is /dev/disk2
if [[ $Device == *"dev"* ]]; then
    echo "Found single external drive: $Info. What number is written on the USB drive?"
    read StickNumber
    Label=$StickNumber"_B-HUMAN"

    diskutil eraseDisk exFAT $Label MBRFormat $Device
    ExitStatus=$?

    if [ $ExitStatus -eq 0 ]; then
        echo ""
        echo ""
        diskutil eject $Device

        echo "   _____ _    _  _____ _____ ______  _____ _____ ";
        echo "  / ____| |  | |/ ____/ ____|  ____|/ ____/ ____|";
        echo " | (___ | |  | | |   | |    | |__  | (___| (___  ";
        echo "  \___ \| |  | | |   | |    |  __|  \___ \\___ \ ";
        echo "  ____) | |__| | |___| |____| |____ ____) |___) |";
        echo " |_____/ \____/ \_____\_____|______|_____/_____/ ";
        echo "                                                 ";
        echo "                                                 ";
        echo "$Device is now named $Label and formatted as exFAT using MBR"
        echo "It should be safe to eject"
    else
        echo "diskutil failed with exit status $ExitStatus"
    fi
else
    echo "Error: No drive detected."
    exit 1
fi
