#!/bin/bash
pushd "$(dirname $0)" >/dev/null
../../Util/SimRobot/Util/mare/Linux/bin/mare --codelite && sed <SimRobot.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp && mv /tmp/mare.tmp SimRobot.project && sed <bush.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp && mv /tmp/mare.tmp bush.project
QTINCLUDE=`qtchooser -qt=qt5-x86_64-linux-gnu -print-env | grep QTTOOLDIR | sed "s%QTTOOLDIR=\"\(.*\)bin\"%\1%" | sed "s/^\/usr\/lib/\/usr\/include/"`
SSSE3=`(grep ssse3 </proc/cpuinfo ; echo 'ssse3=false') | head -1 | sed 's/.*ssse3 .*/ssse3=true/'`
AVX2=`(grep avx2 </proc/cpuinfo ; echo 'avx2=false') | head -1 | sed 's/.*avx2 .*/avx2=true/'`
FLAGS=$SSSE3' '$AVX2
for i in *.project; do
  sed <"$i" "s%/bin/mare %/bin/mare qtinclude=\"$QTINCLUDE\" $FLAGS %" >/tmp/generate.tmp && mv /tmp/generate.tmp "$i"
done
popd >/dev/null

