#!/bin/bash
pushd "$(dirname "$(which "$0")")" >/dev/null
../../Util/SimRobot/Util/mare/Linux/bin/mare --codelite \
&& sed <SimRobot.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp \
&& mv /tmp/mare.tmp SimRobot.project \
&& sed <bush.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp \
&& mv /tmp/mare.tmp bush.project
QTINCLUDE=`for d in $(find /usr/include /usr/local/include -name qt5 \( -type l -or -type d \)); do [ -d \$d/QtCore ] && echo \$d; done | head -n1`
CLANGINCLUDE=`for d in $(clang++ -c -v -E - </dev/null 2>&1 | sed -n -e '/here:/,/^End/{/here:/d; /^End/d; p}'); do [ -f \$d/xmmintrin.h ] && echo \$d; done | head -n1`
SSSE3=`(grep ssse3 </proc/cpuinfo
        echo 'ssse3=false') \
       | head -1 \
       | sed 's/.*ssse3 .*/ssse3=true/'`
AVX2=`(grep avx2 </proc/cpuinfo
       echo 'avx2=false') \
      | head -1 \
      | sed 's/.*avx2 .*/avx2=true/'`
FLAGS=$SSSE3' '$AVX2
for i in *.project; do
  sed <"$i" "s%/bin/mare %/bin/mare qtinclude=\"$QTINCLUDE\" clanginclude=\"$CLANGINCLUDE\" $FLAGS %" >/tmp/generate.tmp \
  && mv /tmp/generate.tmp "$i"
done
popd >/dev/null

