#! /bin/bash

usage() {
  >&2 echo "usage: $0 <source image> <target device>"
}

if [ $# -ne 2 ]; then
  usage
  exit 2
fi

if [ $(uname) == "Darwin" -a "$UID" != 0 ]; then
  sudo "$0" "$@"
  exit $?
fi

SOURCE_IMAGE="$1"
TARGET_DEVICE="$2"

if [ ! -f "${SOURCE_IMAGE}" ]; then
  >&2 echo "Source image is not a regular file."
  exit 10
fi

if [ ! $(head -c 8 "${SOURCE_IMAGE}") == "ALDIMAGE" ]; then
  >&2 echo "Source image does not have ALDIMAGE signature."
  exit 11
fi

if [ ! -b "${TARGET_DEVICE}" ]; then
  >&2 echo "Target device is not a block device."
  exit 12
fi

if [ ! -w "${TARGET_DEVICE}" ]; then
  >&2 echo "Target device is not writable."
  exit 13
fi

if [ $(uname) == "Darwin" ]; then
  INFO="$(diskutil information "${TARGET_DEVICE}" 2>/dev/null)"
  if [ -z "$(diskutil list "${TARGET_DEVICE}" 2>/dev/null)" ]; then
    DEVICE_TYPE=
  else
    DEVICE_TYPE=disk
  fi
  DEVICE_REMOVABLE="$(grep <<<"$INFO" '^ *Removable Media:' \
                      | sed 's%^.*: *Removable.*% 1%')"
  DEVICE_MOUNTPOINT="$(mount | grep "^${TARGET_DEVICE}")"
  DEVICE_SIZE="$(grep <<<"$INFO" '^ *Disk Size:' | sed 's%[^(]*(\([0-9]*\).*%\1%')"
  IMAGE_SIZE=$(stat -f%z "${SOURCE_IMAGE}")
else
  DEVICE_TYPE=$(lsblk "${TARGET_DEVICE}" -ndo TYPE)
  DEVICE_REMOVABLE=$(lsblk "${TARGET_DEVICE}" -ndo RM)
  DEVICE_MOUNTPOINT=$(lsblk "${TARGET_DEVICE}" -no MOUNTPOINT)
  DEVICE_SIZE=$(lsblk "${TARGET_DEVICE}" -ndbo SIZE)
  IMAGE_SIZE=$(stat -c%s "${SOURCE_IMAGE}")
fi

if [ "${DEVICE_TYPE}" != "disk" ]; then
  >&2 echo "Target device is not a disk."
  exit 14
fi

if [ "${DEVICE_SIZE}" -lt "${IMAGE_SIZE}" ]; then
  >&2 echo "Target device is too small."
  exit 15
fi

if [ "${DEVICE_REMOVABLE}" != " 1" ]; then
  >&2 echo "Target device is not removable."
  exit 16
fi

if [ "${DEVICE_MOUNTPOINT}" != "" ]; then
  >&2 echo "Target device is mounted."
  exit 17
fi

dd if="${SOURCE_IMAGE}" of="${TARGET_DEVICE}" status=progress bs=1M oflag=sync
if [ $? -ne 0 ]; then
  >&2 echo "Could not transfer image to device."
  exit 18
fi

echo "Flashing ${SOURCE_IMAGE} to ${TARGET_DEVICE} is done."
exit 0
