/**
 * @file MessageIDs.h
 *
 * Declaration of ids for debug messages.
 *
 * @author Martin Lötzsch
 */

#pragma once

#include "Streaming/Enum.h"

/**
 * IDs for debug messages
 *
 * To distinguish debug messages, they all have an id.
 */
ENUM(MessageID,
{,
  idNumOfDataMessageIDs,
  undefined = idNumOfDataMessageIDs,
  idFrameBegin,
  idFrameFinished,

  // Data message IDs used in RobotConsole. Keep them the same over time.
  idActivationGraph,
  idAnnotation,
  idCameraImage,
  idJointCalibration,
  idJointRequest,
  idJointSensorData,
  idJPEGImage,
  idMotionRequest,
  idRawInertialSensorData,
  idStopwatch,

  // Data message IDs not used in RobotConsole. They can change over time.
  idAgentStates,
  idAlternativeRobotPoseHypothesis,
  idArmMotionRequest,
  idAudioData,
  idBallModel,
  idBallPercept,
  idBallSpots,
  idBehaviorStatus,
  idBodyContour,
  idCalibrationRequest,
  idCameraCalibration,
  idCameraCalibrationStatus,
  idCameraInfo,
  idCameraMatrix,
  idCirclePercept,
  idCustomCalibrationLines,
  idFallDownState,
  idFieldBoundary,
  idFootSupport,
  idFrameInfo,
  idFsrSensorData,
  idGameControllerData,
  idGameState,
  idGlobalOpponentsModel,
  idGlobalTeammatesModel,
  idGroundContactState,
  idGroundTruthOdometryData,
  idGroundTruthWorldState,
  idGyroOffset,
  idHeadMotionInfo,
  idHeadMotionRequest,
  idIMUCalibration,
  idIMUValueState,
  idImageCoordinateSystem,
  idIndirectKick,
  idInertialData,
  idInertialSensorData,
  idJointAnglePred,
  idJointAngles,
  idJointLimits,
  idJointPlay,
  idJoystickState,
  idKeyStates,
  idLinesPercept,
  idModifiedJointRequest,
  idMotionInfo,
  idMotionRobotHealth,
  idObstacleModel,
  idObstaclesFieldPercept,
  idObstaclesImagePercept,
  idOdometer,
  idOdometryData,
  idOdometryDataPreview,
  idOdometryTranslationRequest,
  idPenaltyMarkPercept,
  idReceivedTeamMessages,
  idRefereeGesture,
  idRefereeSignal,
  idRobotDimensions,
  idRobotHealth,
  idRobotPose,
  idRobotStableState,
  idSelfLocalizationHypotheses,
  idSideInformation,
  idSkillRequest,
  idSolePressureState,
  idStaticJointPoses,
  idStrategyStatus,
  idSystemSensorData,
  idTeamData,
  idTeamBallModel,
  idTorsoMatrix,
  idWalkGenerator,
  idWalkLearner,
  idWalkStepData,
  idWalkingEngineOutput,
  idWhistle,
  numOfDataMessageIDs, /**< everything below this does not belong into log files */

  // infrastructure
  idConsole = numOfDataMessageIDs,
  idDebugDataChangeRequest,
  idDebugDataResponse,
  idDebugDrawing,
  idDebugDrawing3D,
  idDebugImage,
  idDebugRequest,
  idDebugResponse,
  idDrawingManager,
  idDrawingManager3D,
  idLogResponse,
  idModuleRequest,
  idModuleTable,
  idPlot,
  idRobotName,
  idText,
  idThread,
  idTypeInfo,
  idTypeInfoRequest,
});
