#!/bin/bash

if [ -z "${bhDir:-""}" ]; then
  echo "This script is only useful when included into other scripts"
  exit 125
fi

robotsFile="${bhDir}/Config/Robots/robots.cfg"

stdout="/dev/null"
stderr="/dev/null"

if [ "${verbosity:-""}" = "" ] ; then
  verbosity=4
fi

if [ "${verbosity}" -ge 6 ]; then
  stdout="/dev/fd/1"
  stderr="/dev/fd/2"
fi

debug() {
  if [ ${verbosity} -lt 5 ]; then
    return
  fi
  echo -n "[DEBUG]  : "
  echo "$@"
}

message() {
  if [ ${verbosity} -lt 4 ]; then
    return
  fi
  echo -n "[INFO]: "
  echo "$@"
}

warning() {
  if [ ${verbosity} -lt 3 ]; then
    return
  fi
  echo -n "[WARNING]: "
  echo "$@"
}

error() {
  echo -n "[ERROR]: "
  echo "$@"
}

fatal() {
  echo -n "[FATAL]: "
  echo "$@"
  exit 1
}

# checkApp
# return if $1 is found, else calls fatal
# $1: application to search for
# $2: optional comment
checkApp() {
  local app="${1:-""}"
  if ! which $app 2>"${stderr}" >"${stdout}" ; then
    if [ -z "${2:-""}" ]; then
      fatal "Can't find the command '$app' on your system!"
    else
      error "Can't find the command '$app' on your system!"
      fatal "${2}"
    fi
    return 1
  fi
}
