#!/bin/bash
pushd "$(dirname "$(which "$0")")" >/dev/null
../../Util/mare/Linux/bin/mare --codelite \
&& sed <SimRobot.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp \
&& mv /tmp/mare.tmp SimRobot.project \
&& sed <bush.project "s%\(<General[^>]*\)/>%\1 IsGUIProgram=\"yes\"/>%" >/tmp/mare.tmp \
&& mv /tmp/mare.tmp bush.project
QTINCLUDE=`for d in $(find /usr/include /usr/local/include -name qt5 \( -type l -or -type d \)); do [ -d \$d/QtCore ] && echo \$d; done | head -n1`
for i in *.project; do
  sed <"$i" "s%/bin/mare %/bin/mare qtinclude=\"$QTINCLUDE\" %" >/tmp/generate.tmp \
  && mv /tmp/generate.tmp "$i"
done
popd >/dev/null

