#!/bin/bash

set -eu

scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
baseDir=$(dirname "${scriptPath}")

cd "$baseDir"

find lib -name "*.prl" | xargs rm
find lib -name "*_debug" | xargs rm

for i in lib/*/Versions/5; do
  cd $(dirname $i)
  if [ ! -e A ]; then
    mv 5 A
    ln -sf A Current
    ln -s A 5
  fi
  cd ../../..
done
