motion_id = stand
"test

label start

stiffness 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 0

"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur
label repeat
  -0.5    2.3   90.0   10.1  -90.0   -8.2  -90.0   0.0    90.5   -9.8   89.8    8.4   90.0    0.0    0.0    0.0  -21.3   48.9  -27.6    0.1    0.0    0.0  -21.2   49.0  -27.6    0.0   1 1000
transition stand stand repeat

transition allMotions extern start
